### ISSUE TITLE
Sign In button on welcome screen should be higher contrast with background

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#33]
Current contrast is too low - mocks had drop shadows, but if that doesn't work a slightly darker gray would do just fine. :)

![screenshot_20180916-163301](https://user-images.githubusercontent.com/36721640/45603261-4918ae80-b9df-11e8-98dd-fc11f496b601.png)

**Comment by william-chu** [comment]
@crieggalder Hi Chris, is there a location for these mocks so I can reference? Thanks!

William

**Comment by crieggalder** [comment]
Yes - glad you asked! Here's the Figma board we're working from: https://www.figma.com/file/cecPCBc0nhNva7VdTOb2DRqh/Civic-Design?node-id=0%3A1

**Comment by william-chu** [comment]
@crieggalder Hi Chris, I've pushed up a branch with these changes, is this correct? I removed the 'or' from the login options and added drop shadows to the buttons, I tested this from my Galaxy S9 so I'm not sure how it will look on a smaller screen. I'll create a pr on my branch if this is correct.
![image](https://user-images.githubusercontent.com/25733358/46576792-6f4ec000-c987-11e8-9266-eb11dd8aac4f.png)
![image](https://user-images.githubusercontent.com/25733358/46576788-61993a80-c987-11e8-8a6f-41324142321a.png)

**Comment by crieggalder** [comment]
@william-chu looks great! Could we make the font on the Register/Sign In buttons the same size as the font on the next screen's buttons? And I think we can make the buttons on the next screen less tall to avoid clipping. So my suggestion is: font size from screen 2, button height from screen 1. Lmk how that turns out!

**Comment by william-chu** [comment]
Drop shadows were added in merged pr and I matched the font size for the buttons. Carousel clipping might be unavoidable on extremely short devices, but I tried using empty flexed components to add responsive spacing on the welcome screen.
