### ISSUE TITLE
Sign In/Register menu obscures circle element above

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#34]
Menu should be small enough to not clip circle element from welcome carousel. I recommend deleting the "or" between FB and email and compressing vertical space throughout the menu. Changes we make here should be reflected on both Sign In and Register. :)

![screenshot_20180916-163404](https://user-images.githubusercontent.com/36721640/45603317-fb507600-b9df-11e8-8394-f21c0872dfa9.png)

**Comment by gmferland** [comment]
This is another one that varies by screen size. For example, on my iPhone SE there is barely enough room for the Register/Sign In buttons when the menu is collapsed. On an iPhone X, moving the circle element up enough to not be obscured by the menu makes it look weird (too much space on the bottom) when the menu is collapsed.

That said, getting rid of "or" could be a good idea

**Comment by marcaaron** [comment]
that "or" needs ta go

**Comment by crieggalder** [comment]
Assigning @william-chu as the "or" slayer! :)

**Comment by william-chu** [comment]
recently merged pr removed 'or' from the sign-in menu
