### ISSUE TITLE
Text fields in email registration shows double underlines; should be single

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#36]
Looks like there's a line from the native element and a line from our custom UI?

![screenshot_20180916-163459](https://user-images.githubusercontent.com/36721640/45603397-8cbfe800-b9e0-11e8-9ea5-a178ebcc5516.png)

**Comment by gmferland** [comment]
This is my bad. It's an example of a component that will look different on iOS and Android. In particular, iOS will not have the underline because that's not part of the iOS style guide. Android renders it natively

**Comment by marcaaron** [comment]
Just to clarify I assumed the fix for this was to get rid of the underline altogether and not try to keep this look consistent across iOS/android by keeping the underline and trying to disable it on android. Fair assumption?

**Comment by crieggalder** [comment]
Yep, sounds good!
