### ISSUE TITLE
Elections icon for bottom menu should be aligned with mocks

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#41]
Currently showing a different icon for Elections in the bottom menu than the icon in our mocks. See Figma for the replacement!

![screenshot_20180916-164027](https://user-images.githubusercontent.com/36721640/45603549-b88f9d80-b9e1-11e8-98b0-5f307043b76f.png)

**Comment by marcaaron** [comment]
Where is the icon from Figma? Is it a custom icon or what?

**Comment by gmferland** [comment]
I couldn’t find an icon similar to the one in Figma in React Native’s
library of vector icons so I went for something close. You can definitely
download the image from Figma and use that, but you would have to download
a gray one and an orange one and have some logic to switch between them
