### ISSUE TITLE
District match zip code input is covered by keyboard with no way to dismiss

### ISSUE THREAD

**Issue by gmferland** [andreisarebi/civic-app#47]
![image](https://user-images.githubusercontent.com/24640381/45791888-8a1bf780-bc59-11e8-8da4-99c32a2d0a45.png)

**Comment by marcaaron** [comment]
What is the proposed fix for this? Is the zip code input area supposed to be visible on focus? Should a tap outside the keypad cancel the user interaction ?

**Comment by gmferland** [comment]
I think the input area should be visible above the keyboard but I'm not
sure exactly how to get that behavior. I always thought the OS would do
that by default. You should be able to supply a "done" button or something
similar on the keyboard so the user can dismiss. In other apps I've used
(Spotify for example) tapping outside the keyboard did not dismiss the
input. I'm not sure if that's a bug or not

**Comment by marcaaron** [comment]
Ok, cool thanks! I figured out the view part at least! There's a view called `KeyboardAvoidingView`. Got it working :)
