### ISSUE TITLE
Activism button off-center, stretched; box clipped

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#64]
Text on the activism button is off-center and the button looks too big on my screen. Desired behavior: button text should be the same size as body text in white box above, and button should constitute a smaller fraction of total box width as in mocks. Additionally, arrow should be positioned just to the right of text or deleted (probably easiest to delete).

Box itself is clipped on the bottom of my smaller screen.

![screenshot_20181003-111511](https://user-images.githubusercontent.com/36721640/46430631-6f885a80-c6fe-11e8-89c0-79555236781f.png)

**Comment by marcaaron** [comment]
Would be helpful to have a reference to the mock-up here.

**Comment by marcaaron** [comment]
![screen shot 315](https://user-images.githubusercontent.com/32969087/46495042-3c5ecd80-c7c9-11e8-9477-9cdb9a4d3a68.png)

this was the mock-up I was provided with

**Comment by william-chu** [comment]
![image](https://user-images.githubusercontent.com/25733358/46544444-71762900-c878-11e8-972e-8ec24712fd2f.png)
I tried to adjust the styling here to meet our requests, I didn't notice the other issue for the button text being centered until after I had fixed it in my branch so it might be duplicated in Marc's other pull req

**Comment by marcaaron** [comment]
Looks good! I can close my PR if ya wanna make a new one for this.

**Comment by marcaaron** [comment]
@crieggalder is this what you had in mind?

**Comment by william-chu** [comment]
I sent a pull request earlier this morning. It should include the center styling on the bottom nav text so this change should take care of both issues?

**Comment by crieggalder** [comment]
Yes, this is great! Thanks @william-chu!
