### ISSUE TITLE
Only Governor and US Senator races showing for users

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#72]
Entered my zip (94549) with a test account and only saw races for Governor and US Senator. @gmferland - I think you were working on filtering the Elections screen by district. Is there anything on that front you can hand off to @marcaaron?

**Comment by gmferland** [comment]
I need to double back on the filtering logic for sure

**Comment by marcaaron** [comment]
So is there a way to confirm whether this is a content issue? I created a new account with your zip code and console logged the output right before the `matchDistrictToElections` function this is what I'm seeing.

```
6:47:07 PM: district:  CA-11
6:47:07 PM: Array [
6:47:07 PM:   "Governor",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "Governor",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "US Senate",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "US Senate",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 39",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 39",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 10",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 10",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 25",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 25",
6:47:07 PM: ]
6:47:07 PM: Array [
6:47:07 PM:   "California District 13",
6:47:07 PM: ]
```

**Comment by marcaaron** [comment]
Checked the google sheet and the candidates are in there. So the problem must be occurring somewhere else ?

**Comment by marcaaron** [comment]
Ah I think I figured it out... just noticed that only a handful of candidates actually have IDs in the google spreadsheet! Might that be the cause of this issue?
