### ISSUE TITLE
Facebook auth not working

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#73]
The Continue with Facebook button takes me to a Facebook sign-in, but signing in produces an error. Looks like it's a problem with our FB dev account settings.

![screenshot_20181006-141138](https://user-images.githubusercontent.com/36721640/46575825-e7aa8680-c971-11e8-8b58-62080a4a414b.png)

**Comment by crieggalder** [comment]
@gmferland feel free to tag @mialknowles or @cgalbiati for this if/when you need to tap out!

**Comment by gmferland** [comment]
Facebook requires we provide urls to our Privacy Policy and Terms of Service in order to make the app public

**Comment by hanagabriellebidon** [comment]
I actually used Facebook to log in and it works for me in Android.

**Comment by crieggalder** [comment]
Nice!!
