### ISSUE TITLE
Bottom Buttons not aligned in the center

### ISSUE THREAD

**Issue by hanagabriellebidon** [andreisarebi/civic-app#79]
![screenshot_20181007-215404_expo](https://user-images.githubusercontent.com/37670365/46590071-9340fd00-ca7e-11e8-9324-9b5d34879874.jpg)

**Comment by crieggalder** [comment]
I think @william-chu addressed this - just waiting for the merge on his latest PR. :)

**Comment by hanagabriellebidon** [comment]
Thank you for letting me know.

**Comment by william-chu** [comment]
This should be fixed in the merged pr
