### ISSUE TITLE
Matches banner icon clipped

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#81]
Megaphone icon on the matches banner (Elections screen) should be vertically centered within the banner and fully visible. Currently too low and clipped. We can rescale dynamically if necessary on small screens.

![a5971d25-29cf-424f-b5be-1b813ea6fbf8](https://user-images.githubusercontent.com/36721640/46699053-8a127600-cbcd-11e8-815d-6a4aabba9f73.png)

**Comment by william-chu** [comment]
I noticed this and I think I fixed it when I was working on the voter registration alert bug, will be included in pr issue80

**Comment by william-chu** [comment]
changes merged in pr issue80
