### ISSUE TITLE
Favorites screen shows mock news

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#82]
The Favorites screen currently shows mock news for a candidate. Until the news feature is ready, let's just use the same components for candidates that we use on the Election screen and filter to only show favorited candidates. This will mean that candidates on the Favorites screen look the same as candidates on the Elections screen. 

![094103fe-72d2-4a7a-a51c-a5ce140c1f53](https://user-images.githubusercontent.com/36721640/46699144-c5ad4000-cbcd-11e8-893d-ea748f978083.png)

**Comment by hanagabriellebidon** [comment]
@vahurtad When do you want to start working on this?

**Comment by vahurtad** [comment]
@hrb56 
Thanks. I already finished this

**Comment by vahurtad** [comment]
Right now it should look like:
![screenshot_20181009-163945](https://user-images.githubusercontent.com/16183561/46709994-f061bd80-cbfa-11e8-9263-bfaf03c61d73.png)
